image: rambabusaravanan/firebase

stages:
  - deploy

cache:
  paths:
    - node_modules/
  key: "$CI_BUILD_REPO"

deploy-dev:
  stage: deploy
  only:
    - Release-test-v2
  script:
    - npm install
    - npm run deploy
