const engLiterals = {
  home: {
    slogan: "FIBBO : The art of expressing youre art",
  },
  navbar: {
    searchItems: "Search Items...",
    verify: "Verify Your Account!",
    collections: "My Collections",
    connectWallet: "Connect Wallet",
  },
  userMenu: {
    profile: "Profile",
    settings: "Settings",
    community: "Community",
    station: "wFTM Station",
    disconnect: "Disconnect",
    darkMode: "Dark Mode",
    autoDarkMode: "Auto Dark Mode",

  },
  filters: {
    filters: "Filters",
    state: "Status",
    onSale: "On Sale",
    offered: "Has Offers",
    onAuction: "On Auction",
    hasBids: "Has Bids",
    clearAll: "Clear All",
  },
  explore: {
    filterSort: "Sort By",
    filterRecently: "Recently Created",
    filterOldest: "Oldest",
    filterRecentlyListed: "Recently Listed",
    filterOldestListed: "Oldest Listed",
    filterHighPrice: "Highest Price",
    filterLowPrice: "Lowest Price",
    filterEnding: "Ending Soon",
  },
  detailNFT: {
    price: "Price",
    price2: "Price:",
    offer: "Offer for",
    collection: "Collection",
    chain: "Chain",
    idchain: "Chain ID",
    idtoken: "Token ID",
    royalties: "Royalties",
    recipient: "Recipient",
    filterHistorial: "Filter Activities",
    sales: "Sales",
    transfers: "Transfers",
    listings: "Listings",
    offers: "Offers",
    auctions: "Auctions",
    offerOf: "Offer of",
    expires: "Expires",
    expiresIn: "Expires in",
    actions: "Actions",
  },
  itemPage: {
    chainData: "Chain Data",
    properties: "Properties",
    activity: "Item Activity",
    moreCollection: "More from this collection",
    offers: "Offers",
    owner: "Owner:",
    refreshMeta : "Refresh Metadata",
    fantomNetwork: "Fantom Network",
    itemFreezed: "This item is frozen",
  },
  itemHistory: {
    event: "Event",
    item: "Item",
    price: "Price",
    initiator: "Initiator",
    recipient: "Recipient",
    date: "Date",
    from: "From",
    to: "To",
  },
  myCollections: {
    mycollections: "My collections",
    text: "Create and manage your exclusives NFT's collections for sharing and selling them",
  },
  createCollection: {
    logo: "Collection logo",
    imgPrincipal: "Collection main image",
    banner: "Collection Banner",
    collectionName: "Collection name",
    collectionName2: "Name:",
    description: "Description",
    description2: "Description:",
    explicit: "Explicit & Sensitive Content",
    logoDesc:
      "Select the logo of the collection that will be visible when browsing the marketplace. The recommended size is 350 x 350.",
    imgPrincipalDesc:
      "Select the main image from the collection. This image will be used to present your collection on the home page or other promotional areas of Fibbo. If no image is selected, the collection logo will be used. The recommended size is 600 x 400.",
    bannerDesc:
      "This image will appear at the top of your collection page. Avoid including too much text in this banner image, as the dimensions change on different devices. The recommended size is 1400 x 350.",
    urlDesc:
      "Customize your URL on Fibbo. Can only contain lowercase letters, numbers, and hyphens.",
    descriptionDesc:
      "The collection description must contain a maximum of 1000 characters.",
    example: "Example: Rock painting",
    descriptionPlaceholder: "Share all the details of your collection",
    selectImage: "Select an image!",
    nameCharacters: "The name must contain between 4 and 30 characters",
    descriptionCharacters:
      "The description must contain between 50 and 1000 characters",
  },
  profile: {
    collected: "Collected",
    created: "Created",
    activity: "Activity",
    offers: "Offers",
    myOffers: "My offers",
    sentence: "Artist verified by Fibbo team",
  },
  profileSettings: {
    settings: "SETTINGS",
    account: "Profile",
    notifications: "Notifications",
    appearance: "Appearance",
    profileSettings: "Profile",
    userName: "User name",
    introduceUserName: "Introduce your username",
    biography: "Biography",
    tellMore: "Tell us more about yourself...",
    email: "Email",
    emailExample: "example@gmail.com",
    wallet: "Wallet",
    profileImg: "Profile image",
    backgroundImg: "Background image",
    selectLenguage: "Select a lenguage:",
    spanish: "Spanish",
    english: "English",
    yourActivityNotifications: "Your Activity Notifications",
    followerActivityNotifications: "Follower Activity Notifications",
  },
  features: {
    suggestions: "Suggestions",
    sentence:
      "Vote and help deciding the evolution of the FIBBO marketplace, the community is the one responsable to add new functionallities to get everyone's product.",
    suggest: "Suggest any change",
    newSuggestion: "New suggestion",
    newSuggestionText:
      "Your suggestion will be reviewed and a value will be assigned by the technical team, once it is accepted and valued it will be shown on the list!",
    newSuggestionTitle: "TITLE",
    newSuggestionDescription: "DESCRIPTION",
    suggestionDoneText:
      "Thank you for your suggestion, we will review your request and process it.",
  },
  makeOffer: {
    offerPrice: "What price do you want to offer?",
    expires: "Expires",
    notWFTM: "You don't have enough WFTM",
    offerOf: "Offer of",
  },
  notifications: {
    notifications: "Notifications",
    noNotifications: "You don't have notifications",
  },
  actions: {
    makeOffer: "Make Offer",
    createCollection: "CREATE COLLECTION",
    addSuggestion: "Make suggestion",
    goToHome: "Go to Homepage",
    verifyAccount: "Verify Account",
    closeWindow: "CLOSE WINDOW",
    saveChanges: "SAVE",
    buyNow: "Buy now",
    makeBid: "Make bid",
    viewYourOffer: "View your offer",
  },
  modals: {
    connectSentence: "Connect a wallet",
    connectMetamask: "Connect with Metamask",
    artistNotVerified:
      "You are not a verified artist so you can't suggest changes, verify your account and be part of the community!",
    artistNotVerified2:
      "You are not a verified artist to be able to create NFTs on the marketplace, verify your account and be part of the community!",
    URLNotFound:
      "The page you are trying to access does not exist, it is a mystery how you have accessed here. You can press the button to go to the page homepage",
    confirmCreation: "Confirm your creation",
  },
};

const espLiterals = {
  home: {
    slogan: "FIBBO : El Arte de expresar tu Arte",
  },
  navbar: {
    searchItems: "Buscar Items...",
    verify: "Verifícate!",
    collections: "Mis Colecciones",
    connectWallet: "Conectar Billetera",
  },
  userMenu: {
    profile: "Perfil",
    settings: "Configuración",
    community: "Comunidad",
    station: "Estación wFTM",
    disconnect: "Desconectar",
    darkMode: "Tema Oscuro",
    autoDarkMode: "Auto Tema Oscuro",
  },
  filters: {
    filters: "Filtros",
    state: "Estado",
    onSale: "En Venta",
    offered: "Ofertado",
    onAuction: "En Subasta",
    hasBids: "Pujado",
    clearAll: "Limpiar Todos",
  },
  explore: {
    filterSort: "Ordenar Por",
    filterRecently: "Creados Recientemente",
    filterOldest: "Mas Antiguos",
    filterRecentlyListed: "Listados Recientemente",
    filterOldestListed: "Listados Mas Antiguos",
    filterHighPrice: "Mas caros",
    filterLowPrice: "Mas Baratos",
    filterEnding: "Termina Antes",
  },
  detailNFT: {
    price: "Precio",
    price2: "Precio:",
    offer: "Ofertado por",
    collection: "Colección",
    chain: "Cadena",
    idchain: "ID Cadena",
    idtoken: "ID Token",
    royalties: "Regalías",
    recipient: "Recipiente",
    filterHistorial: "Filtrar Historial",
    sales: "Ventas",
    transfers: "Transferencias",
    listings: "Listados",
    offers: "Ofertas",
    auctions: "Subastas",
    offerOf: "Oferta de",
    expires: "Expira",
    expiresIn: "Expira en",
    actions: "Acciones",
  },
  itemPage: {
    chainData: "Datos de la cadena",
    properties: "Propiedades",
    activity: "Actividad del Item",
    moreCollection: "Mas de la colección",
    offers: "Ofertas",
    owner: "Pertenece a:",
    refreshMeta : "Refrescar Metadata",
    fantomNetwork: "Red de Fantom",
    itemFreezed: "El item tiene sus datos congelados",
  },
  itemHistory: {
    event: "Evento",
    item: "Item",
    price: "Precio",
    initiator: "Iniciador",
    recipient: "Recipiente",
    date: "Fecha",
    from: "De",
    to: "A",
  },
  myCollections: {
    mycollections: "Mis colecciones",
    text: "Crea y administra tus colecciones de NFTs únicos para poder compartirlos y venderlos.",
  },
  createCollection: {
    logo: "Logo de la colección",
    imgPrincipal: "Imagen principal de la colección",
    banner: "Pancarta de la colección",
    collectionName: "Nombre de la colección",
    collectionName2: "Nombre:",
    description: "Descripción",
    description2: "Descripción:",
    explicit: "Contenido Explícito o Sensible",
    logoDesc:
      "Selecciona el logo de la colección que será visible al navegar por el marketplace. El tamaño recomendado és 350 x 350.",
    imgPrincipalDesc:
      "Selecciona la imagen de presentación de la colección. Esta imagen se utilizará para presentar su colección en la página de inicio u otras áreas promocionales de Fibbo. Si no se selecciona ninguna imagen, se usará el logo de la colección. El tamaño recomendado és 600 x 400.",
    bannerDesc:
      "Esta imagen aparecerá en la parte superior de la página de tu colección. Evite incluir demasiado texto en esta imagen de banner, ya que las dimensiones cambian en diferentes dispositivos. El tamaño recomendado és 1400 x 350.",
    urlDesc:
      "Personaliza tu URL en Fibbo. Solo puede contener letras minúsculas, números y guiones.",
    descriptionDesc:
      "La descripción de la colección debe contener un máximo de 1000 carácteres.",
    example: "Example: Rock painting",
    descriptionPlaceholder: "Cuenta todo detalle acerca de tu colección!",
    selectImage: "Selecciona una imágen!",
    nameCharacters: "El nombre debe tener entre 4 y 30 carácteres",
    descriptionCharacters:
      "La descripción debe tener entre 50 y 1000 carácteres",
  },
  profile: {
    collected: "En posesión",
    created: "Creados",
    activity: "Actividad",
    offers: "Ofertas",
    myOffers: "Mis ofertas",
    sentence: "Artista verificado por el equipo de FIBOO",
  },
  profileSettings: {
    settings: "CONFIGURACIÓN",
    account: "Perfil",
    notifications: "Notificaciones",
    appearance: "Apariencia",
    profileSettings: "Ajustes de perfil",
    userName: "Nombre de usuario",
    introduceUserName: "Introduce tu nombre de usuario",
    biography: "Biografía",
    tellMore: "Cuentanos más acerca de ti...",
    email: "Correo electrónico",
    emailExample: "ejemplo@gmail.com",
    wallet: "Billetera",
    profileImg: "Imagen de perfil",
    backgroundImg: "Imagen de fondo",
    selectLenguage: "Selecciona un idioma",
    spanish: "Español",
    english: "Inglés",
    yourActivityNotifications: "Tus Notificaciones de Actividad",
    followerActivityNotifications: "Notificaciones de Actividad de Seguidores",
  },
  features: {
    suggestions: "Sugerencias",
    sentence:
      "Vota y contribuye a decidir la evolución del marketplace de FIBBO, la comunidad es la desencadenante de los próximos pasos a añadir para conseguir el producto de todos.",
    suggest: "Sugiere algun cambio",
    newSuggestion: "Nueva sugerencia",
    newSuggestionText:
      "Tu sugerencia será revisada y se le asignará un valor por parte del equipo técnico, una vez sea acceptada y valorada se mostrará en la lista!",
    newSuggestionTitle: "TÍTULO",
    newSuggestionDescription: "DESCRIPCIÓN",
    suggestionDoneText:
      "Gracias por tu sugerencia, revisaremos tu solicitud y la procesaremos.",
  },
  makeOffer: {
    offerPrice: "Que precio quieres ofertar?",
    expires: "Fecha de Expiración",
    notWFTM: "No tienes suficientes WFTM",
    offerOf: "Oferta por",
  },
  notifications: {
    notifications: "Notificaciones",
    noNotifications: "No tienes notificaciones",
  },
  actions: {
    makeOffer: "Realizar Oferta",
    createCollection: "CREAR COLECCIÓN",
    addSuggestion: "Añadir Sugerencia",
    goToHome: "Ir al homepage",
    verifyAccount: "Verificarse",
    closeWindow: "CERRAR VENTANA",
    saveChanges: "GUARDAR CAMBIOS",
    buyNow: "Comprar ya",
    makeBid: "Realizar puja",
    viewYourOffer: "Ver tu oferta",
  },
  modals: {
    connectSentence: "Conectar una billetera",
    connectMetamask: "Conectar con Metamask",
    artistNotVerified:
      "No eres un artista verificado para poder sugerir cambios, verifícate y se parte de la comunidad!",
    artistNotVerified2:
      "No eres un artista verificado para poder crear NFTs en el marketplace, verifícate y se parte de la comunidad!",
    URLNotFound:
      "La página a la que intentas acceder no existe, es un misterio cómo has accedido a esta. Puedes pulsar el botón para dirigirte al Homepage de la página",
    confirmCreation: "Confirma tu creación",
  },
};

export { engLiterals, espLiterals };
