const engLiterals = {
  home: {
    slogan: "FIBBO : The art of expressing youre art",
  },
  navbar: {
    searchItems: "Search Items...",
    verify: "Verify Your Account!",
    collections: "My Collections",
    connectWallet: "Connect Wallet",
  },
  userMenu: {
    profile: "Profile",
    settings: "Settings",
    community: "Community",
    station: "wFTM Station",
    disconnect: "Disconnect",
    darkMode: "Dark Mode",
  },
  filters: {
    filters: "Filters",
    state: "Status",
    onSale: "On Sale",
    offered: "Has Offers",
    onAuction: "On Auction",
    hasBids: "Has Bids",
    clearAll: "Clear All",
  },
  explore: {
    filterSort: "Sort By",
    filterRecently: "Recently Created",
    filterOldest: "Oldest",
    filterRecentlyListed: "Recently Listed",
    filterOldestListed: "Oldest Listed",
    filterHighPrice: "Highest Price",
    filterLowPrice: "Lowest Price",
    filterEnding: "Ending Soon",
  },
  detailNFT: {
    price: "Price",
    price2:"Price:",
    offer: "Offer for",
    collection: "Collection",
    chain:"Chain",
    idchain:"Chain ID",
    idtoken:"Token ID",
    royalties: "Royalties",
    recipient: "Recipient",
    filterHistorial: "Filter Activities",
    sales: "Sales",
    transfers:"Transfers",
    listings:"Listings",
    offers:"Offers",
    auctions:"Auctions",
  },
  itemPage: {
    chainData: "Chain Data",
    properties: "Properties",
    activity: "Item Activity",
    moreCollection: "More from this collection",
    offers: "Offers",
  },
  myCollections: {
    mycollections: "My collections",
    text: "Create and manage your exclusives NFT's collections for sharing and selling them",
  },
  createCollection: {
    logo:"Collection logo",
    imgPrincipal:"Collection main image",
    banner:"Collection Banner",
    collectionName:"Collection name",
    description:"Description",
    explicit:"Explicit & Sensitive Content",
    logoDesc:"Select the logo of the collection that will be visible when browsing the marketplace. The recommended size is 350 x 350.",
    imgPrincipalDesc:"Select the main image from the collection. This image will be used to present your collection on the home page or other promotional areas of Fibbo. If no image is selected, the collection logo will be used. The recommended size is 600 x 400.",
    bannerDesc:"This image will appear at the top of your collection page. Avoid including too much text in this banner image, as the dimensions change on different devices. The recommended size is 1400 x 350.",
    urlDesc: "Customize your URL on Fibbo. Can only contain lowercase letters, numbers, and hyphens.",
    descriptionDesc:"The collection description must contain a maximum of 1000 characters.",
    example: "Example: Rock painting",
    descriptionPlaceholder: "Share all the details of your collection",
  },
  profile: {
    collected:"Collected",
    created:"Created",
    activity:"Activity",
    offers:"Offers",
    myOffers:"My offers",
    sentence: "Artist verified by Fibbo team",
  },
  features: {
    suggestions: "Suggestions",
    sentence: "Vote and help deciding the evolution of the FIBBO marketplace, the community is the one responsable to add new functionallities to get everyone's product.",
    suggest: "Suggest any change",
  },
  actions: {
    makeOffer: "Make Offer",
    createCollection: "CREATE COLLECTION",
    addSuggestion: "Make suggestion",
  },
  modals: {
    connectSentence: "Connect a wallet",
    connectMetamask: "Connect with Metamask",
    artistNotVerified: "You are not a verified artist so you can't suggest changes, verify your account and be part of the community!",
    artistNotVerified2: "You are not a verified artist to be able to create NFTs on the marketplace, verify your account and be part of the community!",
  },
};

const espLiterals = {
  home: {
    slogan: "FIBBO : El Arte de expresar tu Arte",
  },
  navbar: {
    searchItems: "Buscar Items...",
    verify: "Verifícate!",
    collections: "Mis Colecciones",
    connectWallet: "Conectar Billetera",
  },
  userMenu: {
    profile: "Perfil",
    settings: "Configuración",
    community: "Comunidad",
    station: "Estación wFTM",
    disconnect: "Desconectar",
    darkMode: "Tema Oscuro",
  },
  filters: {
    filters: "Filtros",
    state: "Estado",
    onSale: "En Venta",
    offered: "Ofertado",
    onAuction: "En Subasta",
    hasBids: "Pujado",
    clearAll: "Limpiar Todos",
  },
  explore: {
    filterSort: "Ordenar Por",
    filterRecently: "Creados Recientemente",
    filterOldest: "Mas Antiguos",
    filterRecentlyListed: "Listados Recientemente",
    filterOldestListed: "Listados Mas Antiguos",
    filterHighPrice: "Mas caros",
    filterLowPrice: "Mas Baratos",
    filterEnding: "Termina Antes",
  },
  detailNFT: {
    price: "Precio",
    price2: "Precio:",
    offer: "Ofertado por",
    collection: "Colección",
    chain: "Cadena",
    idchain: "ID Cadena",
    idtoken: "ID Token",
    royalties: "Regalías",
    recipient: "Recipiente",
    filterHistorial: "Filtrar Historial",
    sales: "Ventas",
    transfers:"Transferencias",
    listings:"Listados",
    offers:"Ofertas",
    auctions:"Subastas",
  },
  itemPage: {
    chainData: "Datos de la cadena",
    properties: "Propiedades",
    activity: "Actividad del Item",
    moreCollection: "Mas de la colección",
    offers: "Ofertas",
  },
  myCollections: {
    mycollections: "Mis colecciones",
    text: "Crea y administra tus colecciones de NFTs únicos para poder compartirlos y venderlos.",
  },
  createCollection: {
    logo:"Logo de la colección",
    imgPrincipal:"Imagen principal de la colección",
    banner:"Pancarta de la colección",
    collectionName:"Nombre de la colección",
    description:"Descripción",
    explicit:"Contenido Explícito o Sensible",
    logoDesc:"Selecciona el logo de la colección que será visible al navegar por el marketplace. El tamaño recomendado és 350 x 350.",
    imgPrincipalDesc:"Selecciona la imagen de presentación de la colección. Esta imagen se utilizará para presentar su colección en la página de inicio u otras áreas promocionales de Fibbo. Si no se selecciona ninguna imagen, se usará el logo de la colección. El tamaño recomendado és 600 x 400.",
    bannerDesc:"Esta imagen aparecerá en la parte superior de la página de tu colección. Evite incluir demasiado texto en esta imagen de banner, ya que las dimensiones cambian en diferentes dispositivos. El tamaño recomendado és 1400 x 350.",
    urlDesc: "Personaliza tu URL en Fibbo. Solo puede contener letras minúsculas, números y guiones.",
    descriptionDesc:"La descripción de la colección debe contener un máximo de 1000 carácteres.",
    example: "Example: Rock painting",
    descriptionPlaceholder: "Cuenta todo detalle acerca de tu colección!",
  },
  profile: {
    collected:"En posesión",
    created:"Creados",
    activity:"Actividad",
    offers:"Ofertas",
    myOffers:"Mis ofertas",
    sentence: "Artista verificado por el equipo de FIBOO",
  },
  features: {
    suggestions: "Sugerencias",
    sentence: "Vota y contribuye a decidir la evolución del marketplace de FIBBO, la comunidad es la desencadenante de los próximos pasos a añadir para conseguir el producto de todos.",
    suggest: "Sugiere algun cambio",
  },
  actions: {
    makeOffer: "Realizar Oferta",
    createCollection: "CREAR COLECCIÓN",
    addSuggestion: "Añadir Sugerencia",

  },
  modals: {
    connectSentence: "Conectar una billetera",
    connectMetamask: "Conectar con Metamask",
    artistNotVerified: "No eres un artista verificado para poder sugerir cambios, verifícate y se parte de la comunidad!",
    artistNotVerified2: "No eres un artista verificado para poder crear NFTs en el marketplace, verifícate y se parte de la comunidad!",
  },
};

export { engLiterals, espLiterals };
